#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_debug_printf : enable

#include "constants.glsl"
#include "edits_ssbo.glsl"
#include "merges_ssbo.glsl"
#include "sdfs.glsl"

// returns signed distance to the smooth union of the two objects
float map(const vec3 p)
{
    const int i = mSSBO.merges[gl_PrimitiveID].first, j = mSSBO.merges[gl_PrimitiveID].second;
    return - (1. / BLEND_STRENGTH) * log2(exp2(-sdf(p, eSSBO.edits[i].type, eSSBO.edits[i].pos, eSSBO.edits[i].scale) * BLEND_STRENGTH)
                                        + exp2(-sdf(p, eSSBO.edits[j].type, eSSBO.edits[j].pos, eSSBO.edits[j].scale) * BLEND_STRENGTH));
}

void main()
{
    debugPrintfEXT("Double rint !");
    reportIntersectionEXT(1.2, 0U);
    return;
    vec3 p = gl_WorldRayOriginEXT;
    vec3 rd = normalize(gl_WorldRayDirectionEXT);

    float t = 0.;
    for(int i = 0; i < MAX_IT; i++)
    {
        float safeDist = map(p);

        if(t > gl_RayTmaxEXT) return;
        
        if(safeDist <= gl_RayTminEXT)
        {
            reportIntersectionEXT(t, 0U);
            return;
        }

        p += rd * safeDist;
        t += safeDist;
    }
}