#version 460
#extension GL_EXT_ray_tracing : require

#include "constants.glsl"
#include "main_payload.glsl"

layout(location = 0) rayPayloadEXT payload_t payload;

layout(set = 0, binding = 0) uniform accelerationStructureEXT bvh;
layout(set = 0, binding = 1, rgba8) uniform image2D image;

void main()
{
    vec2 uv = vec2(gl_LaunchIDEXT.xy) / vec2(gl_LaunchSizeEXT.xy);
    uv = 2. * uv - 1.;    // uv is in [-1, 1]
    uv.x *= 1366. / 768.; // aspect ratio
    uv.y = - uv.y;        // x goes right, y goes up, z towards me

    vec3 cameraPos = vec3(0., 2.0, 14.);
    vec3 rayDir = vec3(uv.x, uv.y, -2. / tan(0.5 * FOV));
    cameraPos.xz *= rot2D(0.1 * 16.);
    rayDir.xz *= rot2D(0.1 * 16.);

    payload.mirrorRay = false;

    /*  void traceRayEXT(accelerationStructureEXT topLevel,
            uint rayFlags,
            uint cullMask,
            uint sbtRecordOffset,
            uint sbtRecordStride,
            uint missIndex,
            vec3 origin,
            float Tmin,
            vec3 direction,
            float Tmax,
            int payload);
    */
    traceRayEXT(bvh, gl_RayFlagsNoneEXT, 0xFF, 0, 2, 0, cameraPos, T_MIN, rayDir, T_MAX, 0);
    vec3 clr = payload.hitColor;
    float shadow = payload.shadow;
    
    // TODO : use a for-loop
    float roughness = payload.mir_rough;
    if(payload.mirrorRay)
    {
        payload.mirrorRay = false;
        traceRayEXT(bvh, gl_RayFlagsNoneEXT, 0xFF, 0, 2, 0, payload.mir_ro, T_MIN, payload.mir_rd, T_MAX, 0);
        clr = mix(payload.hitColor, clr, roughness);
        shadow *= payload.shadow;
    }

    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(clr * shadow, 0.0));
}
