#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_debug_printf : enable

#include "constants.glsl"
#include "main_payload.glsl"
#include "ssbo.glsl"

layout(location = 0) rayPayloadEXT payload_t payload;

layout(set = 0, binding = 0) uniform accelerationStructureEXT bvh;
layout(set = 0, binding = 1, rgba8) uniform image2D image;

void main()
{
    vec2 uv = vec2(gl_LaunchIDEXT.xy) / vec2(gl_LaunchSizeEXT.xy);
    uv = 2. * uv - 1.;    // uv is in [-1, 1]
    uv.x *= 1366. / 768.; // aspect ratio
    uv.y = - uv.y;        // x goes right, y goes up, z towards me

    vec3 cameraPos = vec3(9., 2.2, 19.);
    vec3 rayDir = vec3(uv.x, uv.y, -2. / tan(0.5 * FOV));
    // cameraPos.xz *= rot2D(0.1 * 16.);
    // rayDir.xz *= rot2D(0.1 * 16.);

    payload.mirrorRay = false;
    payload.refractRay = false;
    payload.negativeRay = 1.;

    // debugPrintfEXT("Edit 0 : rounding %f, scale %f, onion %f, blstr %f, bend %f, norm %f, twist %f", ssbo.edits[0].rounding, ssbo.edits[0].scale, ssbo.edits[0].onion, ssbo.edits[0].blendStrength, ssbo.edits[0].bend, ssbo.edits[0].norm, ssbo.edits[0].twist);

    /*  void traceRayEXT(accelerationStructureEXT topLevel,
            uint rayFlags,
            uint cullMask,
            uint sbtRecordOffset,
            uint sbtRecordStride,
            uint missIndex,
            vec3 origin,
            float Tmin,
            vec3 direction,
            float Tmax,
            int payload);
    */
    traceRayEXT(bvh, gl_RayFlagsNoneEXT, 0xFF, 0, 1, 0, cameraPos, T_MIN, rayDir, T_MAX, 0);
    vec3 clr = payload.hitColor;
    float shadow = payload.shadow;

    bool rray = payload.refractRay;
    vec3 rro = payload.refr_ro;
    vec3 rrd = payload.refr_rd;
    
    // TODO : use a for-loop for recursive reflections
    float roughness = payload.mir_rough;
    if(payload.mirrorRay)
    {
        payload.mirrorRay = false;
        traceRayEXT(bvh, gl_RayFlagsNoneEXT, 0xFF, 0, 1, 0, payload.mir_ro, T_MIN, payload.mir_rd, T_MAX, 0);
        clr = mix(clr * payload.hitColor, clr, roughness);
        shadow *= payload.shadow;
        if(payload.refractRay && !rray)
        {
            rray = true;
            rro = payload.refr_ro;
            rrd = payload.refr_rd;
        }
    }
    if(rray) // refraction
    {
        payload.negativeRay = -1.;
        payload.refractRay = false;
        vec3 oldRd = payload.refr_rd;
        // mask is 0xFE to give 1 bit (isNegativeRay) of data to .rint, becomes 0xFC to tell .rchit to skip the shadow ray
        traceRayEXT(bvh, gl_RayFlagsNoneEXT, 0xFC, 0, 1, 0, payload.refr_ro, T_MIN, payload.refr_rd, T_MAX, 0); // the ray is inside the volume 
        payload.negativeRay = 1.;
        if(abs(dot(payload.refr_rd, oldRd)) > 0.)
        {
            // mask is 0x0F to have positive ray but ignore particles, becomes 0x0D to skip shadow
            traceRayEXT(bvh, gl_RayFlagsNoneEXT, 0x0D, 0, 1, 0, payload.refr_ro, T_MIN, payload.refr_rd, T_MAX, 0); // the ray exited the volume
            clr *= payload.hitColor;
            shadow *= payload.shadow;
        }
        else
        {
            // draw what was behind this
            payload.mirrorRay = false;
            traceRayEXT(bvh, gl_RayFlagsNoneEXT, 0x0F, 0, 1, 0, cameraPos, T_MIN, rayDir, T_MAX, 0);
            clr = payload.hitColor;
            shadow = payload.shadow;

            float roughness = payload.mir_rough;
            if(payload.mirrorRay)
            {
                traceRayEXT(bvh, gl_RayFlagsNoneEXT, 0xFF, 0, 1, 0, payload.mir_ro, T_MIN, payload.mir_rd, T_MAX, 0);
                clr = mix(clr * payload.hitColor, clr, roughness);
                shadow *= payload.shadow;
            }
        }
    }

    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(clr * shadow, 0.0));
}
