#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_debug_printf : enable

#include "constants.glsl"
#include "ssbo.glsl"
#include "sdfs.glsl"

hitAttributeEXT vec3 normal;

// returns distance to the closest object in the scene
// computes n-ary exponential smooth minimum
float map(const vec3 p)
{
    float sum = exp2(-sdf(p, ssbo.edits[gl_PrimitiveID].type, getPos(gl_PrimitiveID), ssbo.edits[gl_PrimitiveID].dimensions) * BLEND_STRENGTH);
    for(int e = 0; e < ssbo.edits[gl_PrimitiveID].nbNeighbours; e++)
    {
        sum += exp2(-sdf(p, ssbo.edits[ssbo.edits[gl_PrimitiveID].neighbours[e]].type,
                            getPos(ssbo.edits[gl_PrimitiveID].neighbours[e]),
                            ssbo.edits[ssbo.edits[gl_PrimitiveID].neighbours[e]].dimensions) * BLEND_STRENGTH);
    }
    return -log2(sum) / BLEND_STRENGTH;
}

// central differences
vec3 computeNormal(const vec3 p)
{
    const float eps = 1e-4;
    const vec2 h = vec2(eps,0);
    return normalize( vec3(map(p+h.xyy) - map(p-h.xyy),
                           map(p+h.yxy) - map(p-h.yxy),
                           map(p+h.yyx) - map(p-h.yyx) ) );
}

void main()
{
    vec3 p = gl_WorldRayOriginEXT;
    vec3 rd = normalize(gl_WorldRayDirectionEXT);
    // debugPrintfEXT("Type = %d, Dims = %f %f %f, pos = %f %f %f", ssbo.edits[gl_PrimitiveID].type, ssbo.edits[gl_PrimitiveID].dimensions.x, ssbo.edits[gl_PrimitiveID].dimensions.y, ssbo.edits[gl_PrimitiveID].dimensions.z, getPos(gl_PrimitiveID).x, getPos(gl_PrimitiveID).y, getPos(gl_PrimitiveID).z);
    // reportIntersectionEXT(1., 0U);
    // return;

    float t = 0.;
    for(int i = 0; i < MAX_IT; i++)
    {
        float safeDist = map(p);

        if(t > gl_RayTmaxEXT)
        {
            return;
        }

        if(safeDist <= gl_RayTminEXT)
        {
            normal = computeNormal(p);
            reportIntersectionEXT(t, 0U);
            return;
        }

        p += rd * safeDist;
        t += safeDist;
    }
}