#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_debug_printf : enable

#include "constants.glsl"
#include "ssbo.glsl"
#include "sdfs.glsl"

hitAttributeEXT vec3 normal;

// returns distance to the closest object in the scene
// computes n-ary exponential smooth minimum
float map(const vec3 p)
{
    float sum = exp2(-sdf(p, ssbo.edits[gl_PrimitiveID].type, ssbo.edits[gl_PrimitiveID].pos, ssbo.edits[gl_PrimitiveID].scale) * BLEND_STRENGTH);
    for(int e = 0; e < ssbo.edits[gl_PrimitiveID].nbNeighbours; e++)
    {
        sum += exp2(-sdf(p, ssbo.edits[ssbo.edits[gl_PrimitiveID].neighbours[e]].type, 
                            ssbo.edits[ssbo.edits[gl_PrimitiveID].neighbours[e]].pos, 
                            ssbo.edits[ssbo.edits[gl_PrimitiveID].neighbours[e]].scale) * BLEND_STRENGTH);
    }
    return -log2(sum) / BLEND_STRENGTH;
}

// central differences
vec3 computeNormal(const vec3 p)
{
    const float eps = 1e-4;
    const vec2 h = vec2(eps,0);
    return normalize( vec3(map(p+h.xyy) - map(p-h.xyy),
                           map(p+h.yxy) - map(p-h.yxy),
                           map(p+h.yyx) - map(p-h.yyx) ) );
}

void main()
{
    if(ssbo.edits[gl_PrimitiveID].nbNeighbours > 26)
    debugPrintfEXT("nb neighbours = %d, type = %d, pos = %f %f %f, scale = %f %f %f", ssbo.edits[gl_PrimitiveID].nbNeighbours, ssbo.edits[gl_PrimitiveID].type, ssbo.edits[gl_PrimitiveID].pos.x, ssbo.edits[gl_PrimitiveID].pos.y, ssbo.edits[gl_PrimitiveID].pos.z, ssbo.edits[gl_PrimitiveID].scale.x, ssbo.edits[gl_PrimitiveID].scale.y, ssbo.edits[gl_PrimitiveID].scale.z);
    vec3 p = gl_WorldRayOriginEXT;
    vec3 rd = normalize(gl_WorldRayDirectionEXT);

    float t = 0.;
    for(int i = 0; i < MAX_IT; i++)
    {
        float safeDist = map(p);

        if(t > gl_RayTmaxEXT)
        {
            return;
        }

        if(safeDist <= gl_RayTminEXT)
        {
            normal = computeNormal(p);
            reportIntersectionEXT(t, 0U);
            return;
        }

        p += rd * safeDist;
        t += safeDist;
    }
}