#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_debug_printf : enable

#define MAX_MERGES 8
struct payload_t {
    vec3 hitColor;
    float time;
    int nbHits;
    int hitIds[MAX_MERGES];
    bool shadowRay;
    float softShadow;
    bool mirrorRay;
};

layout(location = 0) rayPayloadInEXT payload_t payload;

void main()
{
    if(payload.nbHits < MAX_MERGES)
        payload.hitIds[payload.nbHits++] = gl_PrimitiveID;
    ignoreIntersectionEXT;
}