#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_debug_printf : enable

#include "constants.glsl"
#include "ssbo.glsl"
#include "sdfs.glsl"

hitAttributeEXT float shadow;

// returns distance to the closest object in the scene
// computes n-ary exponential smooth minimum
float map(const vec3 p, const float blend)
{
    float firstDist = sdf(p, gl_PrimitiveID);
    if(ssbo.edits[gl_PrimitiveID].nbNeighbours == 0)
        return ssbo.edits[gl_PrimitiveID].negative ? (1. / 0.) : firstDist;

    bool atLeastOneNegative = false;
    if(!ssbo.edits[gl_PrimitiveID].negative)
    {
        atLeastOneNegative = true;
        firstDist = -firstDist;
    }
    float sum = exp2(-firstDist * blend);
    for(int e = 0; e < ssbo.edits[gl_PrimitiveID].nbNeighbours; e++)
    {
        float d = sdf(p, ssbo.edits[gl_PrimitiveID].neighbours[e]);
        if(!ssbo.edits[ssbo.edits[gl_PrimitiveID].neighbours[e]].negative)
        {
            atLeastOneNegative = true;
            d = -d;
        }
        sum += exp2(-d * blend);
    }
    
    return (atLeastOneNegative ? 1. : -1.) * log2(sum) / blend;
}

#define SHADOW_SOFTNESS 64
void main()
{
    vec3 p = gl_WorldRayOriginEXT;
    vec3 rd = normalize(gl_WorldRayDirectionEXT);


    float blend = ssbo.edits[gl_PrimitiveID].blendStrength;
    for(int e = 0; e < ssbo.edits[gl_PrimitiveID].nbNeighbours; e++)
    {
        blend = max(blend, ssbo.edits[ssbo.edits[gl_PrimitiveID].neighbours[e]].blendStrength);
    }

    float t = 0.01; p += t * rd;
    shadow = 1.;
    for(int i = 0; i < MAX_IT; i++)
    {
        float safeDist = map(p, blend);

        shadow = min(shadow, SHADOW_SOFTNESS * safeDist / t);

        if(t + safeDist > gl_RayTmaxEXT)
        {
            reportIntersectionEXT(gl_RayTmaxEXT - 0.1, 0U);
            return;
        }

        if(safeDist <= gl_RayTminEXT)
        {
            shadow = 0.;
            reportIntersectionEXT(t, 0U);
            return;
        }

        p += rd * safeDist;
        t += safeDist;
    }
    reportIntersectionEXT(gl_RayTmaxEXT - 0.1, 0U);
}