#version 460
#extension GL_EXT_ray_tracing : require
// #extension GL_EXT_debug_printf : enable

#include "constants.glsl"
#include "ssbo.glsl"
#include "sdfs.glsl"

hitAttributeEXT float shadow;

// returns distance to the closest object in the scene
// computes n-ary exponential smooth minimum
float map(const vec3 p)
{
    edit_t ed = ssbo.edits[gl_PrimitiveID];
    float firstDist = sdf(p, ed.type, ed.dimensions, mat4(ed.transform_l1.x, ed.transform_l1.y, ed.transform_l1.z, ed.transform_l1.w,
                                                          ed.transform_l2.x, ed.transform_l2.y, ed.transform_l2.z, ed.transform_l2.w,
                                                          ed.transform_l3.x, ed.transform_l3.y, ed.transform_l3.z, ed.transform_l3.w,
                                                          0., 0., 0., 1.));
    if(ssbo.edits[gl_PrimitiveID].nbNeighbours == 0) return firstDist;

    float sum = exp2(-firstDist * BLEND_STRENGTH);
    for(int e = 0; e < ssbo.edits[gl_PrimitiveID].nbNeighbours; e++)
    {
        edit_t ee = ssbo.edits[ssbo.edits[gl_PrimitiveID].neighbours[e]];
        sum += exp2(-sdf(p, ee.type, ee.dimensions, mat4(ee.transform_l1.x, ee.transform_l1.y, ee.transform_l1.z, ee.transform_l1.w,
                                                         ee.transform_l2.x, ee.transform_l2.y, ee.transform_l2.z, ee.transform_l2.w,
                                                         ee.transform_l3.x, ee.transform_l3.y, ee.transform_l3.z, ee.transform_l3.w,
                                                         0., 0., 0., 1.)) * BLEND_STRENGTH);
    }
    
    return -log2(sum) / BLEND_STRENGTH;
}

#define SHADOW_SOFTNESS 64
void main()
{
    vec3 p = gl_WorldRayOriginEXT;
    vec3 rd = normalize(gl_WorldRayDirectionEXT);

    float t = 0.1; p += t * rd;
    shadow = 1.;
    for(int i = 0; i < MAX_IT; i++)
    {
        float safeDist = map(p);

        shadow = min(shadow, SHADOW_SOFTNESS * safeDist / t);

        if(t > gl_RayTmaxEXT)
        {
            reportIntersectionEXT(gl_RayTmaxEXT - 0.1, 0U);
            return;
        }

        if(safeDist <= gl_RayTminEXT)
        {
            shadow = 0.;
            reportIntersectionEXT(t, 0U);
            return;
        }

        p += rd * safeDist;
        t += safeDist;
    }
    reportIntersectionEXT(gl_RayTmaxEXT - 0.1, 0U);
}