#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_debug_printf : enable

#include "constants.glsl"
#include "edits_ssbo.glsl"
#include "sdfs.glsl"

void main()
{
    debugPrintfEXT("Simple rint !");
    reportIntersectionEXT(2., 0U);
    return;
    vec3 p = gl_WorldRayOriginEXT;
    vec3 rd = normalize(gl_WorldRayDirectionEXT);

    float t = 0.;
    for(int i = 0; i < MAX_IT; i++)
    {
        float safeDist = sdf(p, eSSBO.edits[gl_PrimitiveID].type, eSSBO.edits[gl_PrimitiveID].pos, eSSBO.edits[gl_PrimitiveID].scale);

        if(t > gl_RayTmaxEXT) return;
        
        if(safeDist <= gl_RayTminEXT)
        {
            reportIntersectionEXT(t, 0U);
            return;
        }

        p += rd * safeDist;
        t += safeDist;
    }
}